set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_HOST_SYSTEM_PROCESSOR})

set(TRIPLE "x86_64-linux-gnu")
set(TRIPLE_UNKNOWN "x86_64-linux-gnu")

set(CMAKE_SYSROOT /)

set(CMAKE_CROSSCOMPILING FALSE)

# set(CMAKE_C_COMPILER ${TRIPLE}-gcc)
# set(CMAKE_CXX_COMPILER ${TRIPLE}-g++)
# set(CMAKE_AR ${TRIPLE}-ar)

# set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# set(CMAKE_LINKER ${TRIPLE}-ld)
# set(CMAKE_AR ${TRIPLE}-ar)
# set(CMAKE_RANLIB ${TRIPLE}-ranlib)
# set(CMAKE_STRIP ${TRIPLE}-strip)
set(CMAKE_C_FLAGS -Wno-error)